### ISSUE TITLE
Issue with non-spherical harmonic fit to antenna response

### ISSUE THREAD

**Issue by cdilullo** [cdilullo/beam_simulator#15]
For some reason, when lmax=0 for nec.fit_antenna_response(), the antenna gain response at az=360 equals 0.

**Comment by jaycedowell** [comment]
Isn’t that what should happen?

**Comment by cdilullo** [comment]
@jaycedowell I meant to say "lmax is None". I.e. when I try fitting a polynomial in frequency for each point on the sky without spherical harmonic decomposition, the resulting pattern has a strip of zeros at az=360 (but not az=0). I'd expect them to match obviously.

**Comment by jaycedowell** [comment]
Hrm.  Missing modulus operator on the azimuth somewhere?

**Comment by cdilullo** [comment]
Ah, didn't realize the NEC models stopped at az=359. Fixed the issue by copying the response for az=0 to az=360.
